<?xml version="1.0" encoding="utf-8"?><testsuite errors="3" failures="0" name="pytest" skips="0" tests="3" time="0.263"><testcase classname="" file="TestCases/test01/test_1.py" name="TestCases.test01.test_1" time="0"><error message="collection failure">ImportError while importing test module &apos;/data/TestCases/test01/test_1.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python2.7/site-packages/six.py:709: in exec_
    exec(&quot;&quot;&quot;exec _code_ in _globs_, _locs_&quot;&quot;&quot;)
TestCases/test01/test_1.py:1: in &lt;module&gt;
    import requests as re
E   ImportError: No module named requests</error></testcase><testcase classname="" file="TestCases/test02/test_2.py" name="TestCases.test02.test_2" time="0"><error message="collection failure">ImportError while importing test module &apos;/data/TestCases/test02/test_2.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python2.7/site-packages/six.py:709: in exec_
    exec(&quot;&quot;&quot;exec _code_ in _globs_, _locs_&quot;&quot;&quot;)
/Users/alex/pythonGitBash/TestCases/test02/test_2.py:1: in &lt;module&gt;
    ???
E   ImportError: No module named requests</error></testcase><testcase classname="" file="TestCases/test03/test_3.py" name="TestCases.test03.test_3" time="0"><error message="collection failure">ImportError while importing test module &apos;/data/TestCases/test03/test_3.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python2.7/site-packages/six.py:709: in exec_
    exec(&quot;&quot;&quot;exec _code_ in _globs_, _locs_&quot;&quot;&quot;)
TestCases/test03/test_3.py:1: in &lt;module&gt;
    import requests as re
E   ImportError: No module named requests</error></testcase></testsuite>